export const MUSCLE_GROUPS = ['Chest', 'Back', 'Shoulders', 'Biceps', 'Triceps', 'Forearms', 'Legs', 'Core'];

export const EQUIPMENT = ['Barbell', 'Dumbbell', 'Cable Machine', 'Bodyweight', 'Machine', 'Kettlebell', 'Bands'];

export const DEFAULT_EXERCISES = [
    {
        id: 'bench-press',
        name: 'Barbell Bench Press',
        muscleGroup: 'Chest',
        equipment: 'Barbell',
        attachment: 'Flat bench, straight bar',
        notes: 'Lie flat on the bench with feet firmly on ground. Lower the bar to mid-chest and press explosively. Keep core tight and avoid bouncing.',
    },
    {
        id: 'incline-bench',
        name: 'Incline Barbell Bench Press',
        muscleGroup: 'Chest',
        equipment: 'Barbell',
        attachment: 'Bench at 30–45°',
        notes: 'Set bench to 30-45 degree incline. Lower bar to upper chest area. Engage shoulders and chest throughout movement.',
    },
    {
        id: 'cable-fly',
        name: 'Cable Pec Fly',
        muscleGroup: 'Chest',
        equipment: 'Cable Machine',
        attachment: 'Two D-handles, pulleys at shoulder height',
        notes: 'Set cables to shoulder height. Stand in the middle with slight bend in elbows. Bring handles together in a smooth arc.',
    },
    {
        id: 'dumbbell-press',
        name: 'Dumbbell Bench Press',
        muscleGroup: 'Chest',
        equipment: 'Dumbbell',
        attachment: 'Flat or incline bench',
        notes: 'Press dumbbells up and slightly together at the top. Lower with control to chest level. Can be done on flat, incline, or decline bench.',
    },
    {
        id: 'pull-ups',
        name: 'Pull-ups',
        muscleGroup: 'Back',
        equipment: 'Bodyweight',
        attachment: 'Fixed bar, overhand grip',
        notes: 'Grip bar slightly wider than shoulder width. Pull chest to bar, keep elbows close. Full range of motion from dead hang to chin over bar.',
    },
    {
        id: 'lat-pulldown',
        name: 'Lat Pulldown',
        muscleGroup: 'Back',
        equipment: 'Cable Machine',
        attachment: 'Wide bar, high pulley',
        notes: 'Pull the bar down to chest level with elbows tracking behind body. Squeeze lats at bottom of movement. Control the weight on the way up.',
    },
    {
        id: 'barbell-row',
        name: 'Barbell Row',
        muscleGroup: 'Back',
        equipment: 'Barbell',
        attachment: 'Straight bar',
        notes: 'Hinge at hips with slight knee bend. Row bar to lower chest, keeping core tight. Retract shoulder blades and drive elbows back.',
    },
    {
        id: 'face-pull',
        name: 'Face Pull',
        muscleGroup: 'Back',
        equipment: 'Cable Machine',
        attachment: 'Rope attachment, pulley above head height',
        notes: 'Pull rope attachment to face level with elbows high. Explosive pull to engage rear delts. Great for shoulder health and posture.',
    },
    {
        id: 'seated-row',
        name: 'Seated Cable Row',
        muscleGroup: 'Back',
        equipment: 'Cable Machine',
        attachment: 'Close-grip V-handle, low pulley',
        notes: 'Sit tall with a slight knee bend and pull the handle to your navel. Drive the elbows straight back and squeeze the mid-back. Let the weight stretch the lats on the return.',
    },
    {
        id: 'shoulder-press',
        name: 'Barbell Shoulder Press',
        muscleGroup: 'Shoulders',
        equipment: 'Barbell',
        attachment: 'Straight bar, rack at shoulder height',
        notes: 'Press bar from shoulders overhead in a straight line. Keep core engaged. Full lockout at the top, controlled descent.',
    },
    {
        id: 'lateral-raise',
        name: 'Dumbbell Lateral Raise',
        muscleGroup: 'Shoulders',
        equipment: 'Dumbbell',
        attachment: '',
        notes: 'Lift dumbbells to shoulder height with slight elbow bend. Keep wrists neutral. Raise under control with minimal momentum.',
    },
    {
        id: 'machine-shoulder',
        name: 'Machine Shoulder Press',
        muscleGroup: 'Shoulders',
        equipment: 'Machine',
        attachment: '',
        notes: 'Adjust seat height so handles align with shoulders. Press forward and slightly up. Follow the natural path of the machine.',
    },
    {
        id: 'barbell-curl',
        name: 'Barbell Curl',
        muscleGroup: 'Biceps',
        equipment: 'Barbell',
        attachment: 'Straight or EZ bar',
        notes: 'Keep elbows stationary at sides. Curl bar up to shoulder height. Lower with control without full elbow lockout at bottom.',
    },
    {
        id: 'dumbbell-curl',
        name: 'Dumbbell Curl',
        muscleGroup: 'Biceps',
        equipment: 'Dumbbell',
        attachment: '',
        notes: 'Can perform alternate or simultaneous curls. Maintain strict form with minimal swinging. Full range from extended to contracted position.',
    },
    {
        id: 'cable-curl',
        name: 'Cable Curl',
        muscleGroup: 'Biceps',
        equipment: 'Cable Machine',
        attachment: 'Straight bar, low pulley',
        notes: 'Constant tension on biceps throughout set. Elbows stay pinned. Smooth and controlled movement without momentum.',
    },
    {
        id: 'tricep-dips',
        name: 'Tricep Dips',
        muscleGroup: 'Triceps',
        equipment: 'Bodyweight',
        attachment: 'Parallel bars or dip station',
        notes: 'Lower body until elbows reach 90 degrees. Keep body upright to target triceps. Can add weight or use assisted machine for reps.',
    },
    {
        id: 'rope-pushdown',
        name: 'Rope Pushdown',
        muscleGroup: 'Triceps',
        equipment: 'Cable Machine',
        attachment: 'Rope attachment, high pulley',
        notes: 'Keep elbows stationary and high. Push rope down and spread ends apart at the bottom. Peak contraction at full extension.',
    },
    {
        id: 'skull-crusher',
        name: 'Skull Crusher (EZ Bar)',
        muscleGroup: 'Triceps',
        equipment: 'Barbell',
        attachment: 'EZ bar, flat bench',
        notes: 'Lie on flat bench holding EZ bar above chest. Lower bar behind head with bent elbows. Press bar back to start position.',
    },
    {
        id: 'hammer-curl',
        name: 'Hammer Curl',
        muscleGroup: 'Forearms',
        equipment: 'Dumbbell',
        attachment: '',
        notes: 'Hold dumbbells with palms facing in and curl without rotating the wrist. Keep elbows tucked to the ribs. Hits the brachialis and forearm alongside the biceps.',
    },
    {
        id: 'squats',
        name: 'Barbell Back Squat',
        muscleGroup: 'Legs',
        equipment: 'Barbell',
        attachment: 'Squat rack, straight bar',
        notes: 'Descend to parallel or below with chest up and knees tracking over toes. Drive through heels to stand. Core stays braced throughout.',
    },
    {
        id: 'leg-press',
        name: 'Leg Press Machine',
        muscleGroup: 'Legs',
        equipment: 'Machine',
        attachment: '',
        notes: 'Feet shoulder-width apart on platform. Lower weight until knees reach 90 degrees. Drive through full foot to extend.',
    },
    {
        id: 'leg-curl',
        name: 'Leg Curl Machine',
        muscleGroup: 'Legs',
        equipment: 'Machine',
        attachment: '',
        notes: 'Curl the pad toward glutes in a controlled manner. Squeeze hamstrings at the top. Lower with control.',
    },
    {
        id: 'deadlift',
        name: 'Barbell Deadlift',
        muscleGroup: 'Legs',
        equipment: 'Barbell',
        attachment: 'Straight bar, from floor',
        notes: 'Start with bar over mid-foot. Drive through heels and extend hips. Keep bar close to body throughout. Lock out at top.',
    },
    {
        id: 'leg-extension',
        name: 'Leg Extension Machine',
        muscleGroup: 'Legs',
        equipment: 'Machine',
        attachment: '',
        notes: 'Extend legs to full knee extension and squeeze quads. Control the weight on the descent. No jerking or bouncing.',
    },
    {
        id: 'romanian-deadlift',
        name: 'Romanian Deadlift',
        muscleGroup: 'Legs',
        equipment: 'Barbell',
        attachment: 'Straight bar, from rack',
        notes: 'Start standing and hinge at the hips with a soft knee bend, sliding the bar down the thighs. Stop when you feel a deep hamstring stretch. Drive the hips forward to stand.',
    },
    {
        id: 'crunch',
        name: 'Cable Crunch',
        muscleGroup: 'Core',
        equipment: 'Cable Machine',
        attachment: 'Rope attachment, high pulley',
        notes: 'Hold rope attachment behind head. Crunch forward by flexing abs, driving elbows toward hips. Feel contraction in upper abs.',
    },
    {
        id: 'ab-wheel',
        name: 'Ab Wheel Rollout',
        muscleGroup: 'Core',
        equipment: 'Bodyweight',
        attachment: 'Ab wheel',
        notes: 'Kneel and grip the wheel. Roll forward extending body, then roll back using core. Maintain neutral spine throughout.',
    },
    {
        id: 'plank',
        name: 'Plank Hold',
        muscleGroup: 'Core',
        equipment: 'Bodyweight',
        attachment: '',
        notes: 'Forearms on ground, body in straight line from head to heels. Engage core and glutes. Avoid hips sagging or hiking.',
    },
];
